version: "3.9"

networks:
  app-tier:
    driver: bridge

volumes:
  postgres_data:

name: ${DB_NAME}

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${LOCAL_DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    networks:
      - app-tier