name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
      branches:
        - 'main'

jobs:
  test-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
              java-version: '21'
              distribution: 'temurin'
              architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run test with Gradle Wrapper
        run: ./gradlew test --tests "me.macao.test.BusinessTest"